# -*- coding: utf-8 -*-
"""Pairs_Trading_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smFFJzzwxHaYwuw3RndROm6JdcHSkY5q
"""

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

from itertools import combinations
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import roc_auc_score

import statsmodels.api as sm
from statsmodels.tsa.stattools import coint

TICKERS = [
    "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS",
    "ITC.NS","LT.NS","SBIN.NS","AXISBANK.NS","KOTAKBANK.NS"
]

prices = yf.download(TICKERS, start="2016-01-01", progress=False, auto_adjust=False)["Adj Close"]
log_prices = np.log(prices).dropna()
returns = log_prices.diff().dropna()

features = pd.DataFrame({
    "vol": returns.std(),
    "mean_ret": returns.mean(),
    "skew": returns.skew(),
    "kurt": returns.kurt()
})

X_feat = StandardScaler().fit_transform(features)
features["cluster"] = AgglomerativeClustering(n_clusters=4).fit_predict(X_feat)

candidate_pairs = []
for c in features.cluster.unique():
    names = features[features.cluster == c].index.tolist()
    candidate_pairs += list(combinations(names, 2))

pairs = []
for s1, s2 in candidate_pairs:
    _, pval, _ = coint(log_prices[s1], log_prices[s2])
    if pval < 0.05:
        pairs.append((s1, s2))

print("Pairs used:")
pairs

def kalman_beta(y, x):
    beta, P = 0.0, 1.0
    Q, R = 1e-5, 0.001
    betas = []

    for i in range(len(y)):
        P += Q
        K = P * x[i] / (x[i]**2 * P + R)
        beta += K * (y[i] - beta * x[i])
        P *= (1 - K * x[i])
        betas.append(beta)

    return np.array(betas)

ENTRY_Z = 2.0
EXIT_Z = 0.5

def compute_spread(pair):
    y = log_prices[pair[0]].values
    x = log_prices[pair[1]].values
    beta = kalman_beta(y, x)
    spread = y - beta * x
    z = (spread - spread.mean()) / spread.std()
    return spread, z

def generate_positions(z):
    pos = np.zeros(len(z))
    for i in range(1, len(z)):
        if z[i] > ENTRY_Z:
            pos[i] = -1
        elif z[i] < -ENTRY_Z:
            pos[i] = 1
        elif abs(z[i]) < EXIT_Z:
            pos[i] = 0
        else:
            pos[i] = pos[i-1]
    return pos

X, y = [], []

for pair in pairs:
    spread, z = compute_spread(pair)
    for t in range(60, len(z)-5):
        X.append([
            z[t],
            abs(z[t]),
            np.std(spread[t-20:t]),
            np.mean(np.diff(spread[t-5:t]))
        ])
        # label = successful mean reversion
        y.append(int(spread[t+5] * np.sign(z[t]) < 0))

X, y = np.array(X), np.array(y)

split = int(0.7 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

rf = RandomForestClassifier(
    n_estimators=400,
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

clf = CalibratedClassifierCV(rf, method="isotonic")
clf.fit(X_train, y_train)

ml_prob = clf.predict_proba(X_test)[:,1]
print("ROC-AUC:", roc_auc_score(y_test, ml_prob))

vol_regime = (
    returns.rolling(20).std().mean(axis=1) >
    returns.rolling(20).std().mean(axis=1).median()
).astype(int)

confidence = ml_prob * (1 - vol_regime.iloc[-len(ml_prob):].values)
position_size = confidence / np.nanmax(confidence)

def pair_pnl(pair, position_size):
    spread, z = compute_spread(pair)
    pos = generate_positions(z)
    pnl = pos[:-1] * np.diff(spread)
    pnl = pnl[-len(position_size):] * position_size
    return pnl

pair_pnls = {}
for pair in pairs:
    pair_pnls[pair] = pair_pnl(pair, position_size)

portfolio_pnl = np.sum(np.vstack(list(pair_pnls.values())), axis=0)
returns_series = pd.Series(portfolio_pnl)

def sharpe_ratio(r):
    return np.sqrt(252) * r.mean() / r.std()

def max_drawdown(r):
    cum = r.cumsum()
    drawdown = cum - cum.cummax()
    return drawdown.min(), drawdown

print("Sharpe:", sharpe_ratio(returns_series))
mdd, dd_series = max_drawdown(returns_series)
print("Max Drawdown:", mdd)

returns_series.cumsum().plot(figsize=(10,4), title="Equity Curve")
plt.show()

dd_series.plot(figsize=(10,4), title="Drawdown")
plt.show()

import shap

final_rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

final_clf = CalibratedClassifierCV(final_rf, method="isotonic")
final_clf.fit(X_train, y_train)

trained_rf = final_clf.calibrated_classifiers_[0].estimator

assert hasattr(trained_rf, "estimators_"), "RandomForest not fitted properly"

explainer = shap.TreeExplainer(trained_rf)

shap_values = explainer.shap_values(X_test)[:, :, 1]

feature_names = [
    "zscore",
    "|zscore|",
    "spread_vol",
    "spread_momentum"
]

shap.summary_plot(
    shap_values,
    X_test,
    feature_names=feature_names,
    plot_type="bar"
)

shap.summary_plot(
    shap_values,
    X_test,
    feature_names=feature_names
)

shap.force_plot(
    explainer.expected_value[1],
    shap_values[i],
    X_test[i],
    feature_names=feature_names,
    matplotlib=True
)